"""empty message

Revision ID: 548b737ef1d6
Revises: e984ce45a7fb
Create Date: 2019-04-25 13:38:07.431989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548b737ef1d6'
down_revision = 'e984ce45a7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wish', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wish')
    # ### end Alembic commands ###
